"""
ETL Pipeline: Load IPL ball-by-ball data from CSV into MySQL database.

This module performs Extract-Transform-Load operations to:
- Read cleaned IPL CSV (data/processed/cleaned_IPL.csv)
- Create normalized MySQL schema (ipl_db)
- Insert dimensions: teams, venues, players
- Insert facts: matches, deliveries
- Enrich player metadata: batting_style, bowling_arm, bowling_type
- Populate venue_conditions from optional external CSVs

Database Configuration:
- Host: 127.0.0.1
- User: ipl_user
- Password: password123
- Database: ipl_db

Schema is defined in: mysql_schema.sql

Usage:
    python import_ipl.py

Expected Files:
    Required: data/processed/cleaned_IPL.csv
    Optional:
        - data/raw/player_profile.csv (player metadata with batting/bowling style)
        - data/raw/venue_conditions.csv (venue characteristics)

Notes:
    - Uses REPLACE IGNORE to handle duplicate rows
    - Chunks deliveries (10k batches) to avoid memory issues
    - Normalizes player names for fuzzy matching
    - Builds outfield speed proxy from ball-by-ball data
    - Columns in profile CSVs support multiple aliases for flexibility
"""
import pandas as pd
import mysql.connector
from datetime import datetime
import numpy as np
from pathlib import Path
import logging

# Configure logging
logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# Path to the CSV (Using the cleaned version generated by EDA/process.py)
csv_path = "./data/processed/cleaned_IPL.csv"
RAW_DIR = Path("./data/raw")
PROCESSED_DIR = Path("./data/processed")

# Player profile CSV candidates (with multiple alias support)
PLAYER_STYLE_CANDIDATES = [
    RAW_DIR / "player_profile.csv",
    RAW_DIR / "ipl_players_data.csv",
    RAW_DIR / "ipl_players.csv",
    RAW_DIR / "player_styles.csv",
    PROCESSED_DIR / "player_styles.csv",
]

# Venue conditions CSV candidates
VENUE_CONDITION_CANDIDATES = [
    RAW_DIR / "venue_conditions.csv",
    PROCESSED_DIR / "venue_conditions.csv",
]

# MySQL connection details (update if using different credentials)
DB_HOST = "127.0.0.1"
DB_USER = "ipl_user"
DB_PASSWORD = "password123"
DB_NAME = "ipl_db"

# Batch size for bulk delivery inserts (optimize for memory)
DELIVERY_BATCH_SIZE = 10000


def main():
    """Main ETL pipeline orchestrator.
    
    Executes the full pipeline:
    1. Load and validate CSV
    2. Connect to MySQL
    3. Create schema and dimensions
    4. Build player/venue lookups
    5. Enrich player metadata
    6. Enrich venue conditions
    7. Load matches and deliveries
    
    Raises:
        FileNotFoundError: If cleaned_IPL.csv not found
        mysql.connector.Error: If database connection fails
    """
    print("Loading CSV into Pandas...")
    try:
        df = pd.read_csv(csv_path, low_memory=False)
    except Exception as e:
        print(f"Error loading CSV: {e}")
        return

    print("Connecting to MySQL...")
    try:
        conn = mysql.connector.connect(
            host=DB_HOST,
            user=DB_USER,
            password=DB_PASSWORD
        )
        cursor = conn.cursor()
        
        with open("./mysql_schema.sql", 'r') as f:
            sql_script = f.read()
            
        print("Ensuring Database and Tables exist...")
        # Split by semicolon and execute individually to avoid 'multi' keyword issues
        statements = [s.strip() for s in sql_script.split(';') if s.strip()]
        for statement in statements:
            cursor.execute(statement)

        cursor.execute(f"USE {DB_NAME}")

        cursor.execute("ALTER TABLE players ADD COLUMN IF NOT EXISTS batting_style VARCHAR(32) NULL")
        cursor.execute("ALTER TABLE players ADD COLUMN IF NOT EXISTS bowling_arm VARCHAR(32) NULL")
        cursor.execute("ALTER TABLE players ADD COLUMN IF NOT EXISTS bowling_type VARCHAR(32) NULL")
            
        
        print("Extracting Dimension Data...")
        
        # 1. Teams
        team_cols = ['batting_team', 'bowling_team', 'toss_winner', 'match_won_by']
        teams = pd.concat([df[c] for c in team_cols if c in df.columns]).dropna().unique()
        for t in teams:
            cursor.execute("INSERT IGNORE INTO teams (team_name) VALUES (%s)", (t,))
        
        # 2. Venues
        venues = df[['venue', 'city']].drop_duplicates().replace({np.nan: 'Unknown'})
        for _, row in venues.iterrows():
            cursor.execute("INSERT IGNORE INTO venues (venue_name, city) VALUES (%s, %s)", (row['venue'], row['city']))
            
        # 3. Players
        player_cols = ['batter', 'bowler', 'non_striker', 'player_out', 'player_of_match']
        players = pd.concat([df[c] for c in player_cols if c in df.columns]).dropna().unique()
        for p in players:
            cursor.execute("INSERT IGNORE INTO players (player_name) VALUES (%s)", (p,))
            
        conn.commit()
        
        # Build lookups
        cursor.execute("SELECT team_name, team_id FROM teams")
        team_map = dict(cursor.fetchall())
        
        cursor.execute("SELECT venue_name, city, venue_id FROM venues")
        venue_map = { (row[0], row[1]): row[2] for row in cursor.fetchall() }
        
        cursor.execute("SELECT player_name, player_id FROM players")
        player_map = dict(cursor.fetchall())

        _import_player_styles(cursor, conn, player_map)
        inferred_outfield_map = _build_outfield_speed_proxy_map(df)
        _import_venue_conditions(cursor, conn, venue_map, inferred_outfield_map)
        
        # Determine team1 and team2 accurately per match 
        # (Since the dataset lacks explicit team1/team2 columns)
        match_teams = df.groupby('match_id')['batting_team'].unique().to_dict()
        
        # Insert Matches 
        print("Processing Matches...")
        match_cols = ['match_id', 'date', 'venue', 'city', 'toss_winner', 'toss_decision', 'match_won_by']
        matches_df = df[match_cols].drop_duplicates(subset=['match_id']).replace({np.nan: None})
        
        for _, row in matches_df.iterrows():
            m_id = row['match_id']
            city_val = row['city'] if row['city'] is not None else 'Unknown'
            venue_id = venue_map.get((row['venue'], city_val))
            
            # Extract teams from the deliveries grouped mapping
            teams_in_match = match_teams.get(m_id, [])
            team1_name = teams_in_match[0] if len(teams_in_match) > 0 else None
            team2_name = teams_in_match[1] if len(teams_in_match) > 1 else None
            
            team1_id = team_map.get(team1_name) if team1_name else None
            team2_id = team_map.get(team2_name) if team2_name else None
            
            toss_winner_id = team_map.get(row['toss_winner']) if row['toss_winner'] else None
            match_won_by_id = team_map.get(row['match_won_by']) if row['match_won_by'] else None
            
            try:
                # Handle generic string parsing (common pattern: YYYY-MM-DD)
                date_val = datetime.strptime(str(row['date']), '%Y-%m-%d').date() if row['date'] else None
            except ValueError:
                date_val = None 
                
            cursor.execute("""
                INSERT IGNORE INTO matches (match_id, match_date, venue_id, team1_id, team2_id, toss_winner_id, toss_decision, match_won_by_id)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """, (m_id, date_val, venue_id, team1_id, team2_id, toss_winner_id, row['toss_decision'], match_won_by_id))
            
        conn.commit()
        
        # Insert Deliveries
        print("Processing Deliveries...")
        delivery_data = []
        for i, row in df.iterrows():
            batting_team_id = team_map.get(row['batting_team'])
            bowling_team_id = team_map.get(row['bowling_team'])
            batter_id = player_map.get(row['batter'])
            bowler_id = player_map.get(row['bowler'])
            
            player_out_val = row.get('player_out')
            player_out_id = player_map.get(player_out_val) if pd.notna(player_out_val) else None
            
            # Wicket Logic
            is_wicket = bool(pd.notna(player_out_val))
            wicket_type = row.get('wicket_kind') if pd.notna(row.get('wicket_kind')) else None
            
            runs_b = int(row['runs_batter']) if pd.notna(row['runs_batter']) else 0
            runs_e = int(row['runs_extras']) if pd.notna(row['runs_extras']) else 0
            
            delivery_data.append((
                row['match_id'], row['innings'], batting_team_id, bowling_team_id, row['over'], row['ball'],
                batter_id, bowler_id, runs_b, runs_e, is_wicket, wicket_type, player_out_id
            ))
            
            if len(delivery_data) >= 10000:
                cursor.executemany("""
                    INSERT IGNORE INTO deliveries (match_id, innings, batting_team_id, bowling_team_id, over_num, ball_num, 
                    batter_id, bowler_id, runs_batter, runs_extras, is_wicket, wicket_type, player_out_id)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """, delivery_data)
                conn.commit()
                delivery_data = []
                print(f"Inserted up to index {i} out of {len(df)}")
                
        # Insert remaining 
        if delivery_data:
            cursor.executemany("""
                INSERT IGNORE INTO deliveries (match_id, innings, batting_team_id, bowling_team_id, over_num, ball_num, 
                batter_id, bowler_id, runs_batter, runs_extras, is_wicket, wicket_type, player_out_id)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, delivery_data)
            conn.commit()
            
        print("ETL Process Complete! Database accurately populated.")

    except mysql.connector.Error as err:
        print(f"MySQL Error: {err}")
    finally:
        if 'conn' in locals() and conn.is_connected():
            cursor.close()
            conn.close()

def _first_existing_csv(candidates):
    for path in candidates:
        if path.exists():
            return pd.read_csv(path, low_memory=False)
    return None


def _normalize_name(value):
    if pd.isna(value):
        return ""
    text = str(value).strip().lower()
    text = text.replace(".", " ")
    text = text.replace(",", " ")
    text = text.replace("-", " ")
    text = text.replace("'", " ")
    text = " ".join(text.split())
    return text


def _name_aliases(value):
    """Generate normalized aliases for short-name/full-name matching."""
    text = _normalize_name(value)
    if not text:
        return []

    aliases = {text, text.replace(" ", "")}
    tokens = text.split()

    if len(tokens) >= 2:
        # Build initials aliases like "v kohli" and "vk kohli" from "virat kohli".
        surname = tokens[-1]
        initials_spaced = " ".join(token[0] for token in tokens[:-1]) + f" {surname}"
        initials_compact = "".join(token[0] for token in tokens[:-1]) + f" {surname}"
        aliases.add(initials_spaced)
        aliases.add(initials_compact)
        aliases.add(initials_spaced.replace(" ", ""))
        aliases.add(initials_compact.replace(" ", ""))

    return [alias for alias in aliases if alias]


def _build_player_alias_map(player_map):
    """Build a normalized alias lookup for player IDs.

    Multiple source files may use short names, initials, or full names.
    Keep only unambiguous aliases so we avoid mapping a style record to the
    wrong player.
    """
    alias_map = {}
    collisions = set()

    for name, player_id in player_map.items():
        for alias in _name_aliases(name):
            if alias in collisions:
                continue
            existing = alias_map.get(alias)
            if existing is None:
                alias_map[alias] = player_id
            elif existing != player_id:
                alias_map.pop(alias, None)
                collisions.add(alias)

    return alias_map


def _resolve_player_id(style_row, name_columns, normalized_players, alias_map):
    """Resolve a style row to a player_id using multiple name aliases."""
    for col in name_columns:
        if not col:
            continue
        raw_value = style_row.get(col)
        if pd.isna(raw_value) or str(raw_value).strip() == "":
            continue

        for alias in _name_aliases(raw_value):
            player_id = normalized_players.get(alias) or alias_map.get(alias)
            if player_id:
                return player_id
    return None


def _normalize_batting_style(value):
    text = _normalize_name(value)
    if not text:
        return None
    if "left" in text:
        return "left-handed"
    if "right" in text:
        return "right-handed"
    return text


def _normalize_bowling_arm(value):
    text = _normalize_name(value)
    if not text:
        return None
    if "left" in text:
        return "left-arm"
    if "right" in text:
        return "right-arm"
    return text


def _normalize_bowling_type(value):
    text = _normalize_name(value)
    if not text:
        return None
    if "spin" in text:
        return "spin"
    if any(token in text for token in ["pace", "fast", "medium", "seam"]):
        return "pace"
    return text


def _null_if_blank(value):
    if pd.isna(value):
        return None
    text = str(value).strip()
    return None if text == "" else value


def _build_outfield_speed_proxy_map(df):
    required_cols = {"venue", "season", "runs_batter"}
    if not required_cols.issubset(df.columns):
        print("Could not infer outfield speed: required columns missing in cleaned IPL data.")
        return {}

    proxy_df = df[["venue", "season", "runs_batter"]].copy()
    proxy_df["city"] = df["city"] if "city" in df.columns else ""

    proxy_df["season"] = pd.to_numeric(proxy_df["season"], errors="coerce")
    proxy_df["runs_batter"] = pd.to_numeric(proxy_df["runs_batter"], errors="coerce").fillna(0)
    proxy_df = proxy_df.dropna(subset=["season"])
    if proxy_df.empty:
        print("Could not infer outfield speed: no valid season rows available.")
        return {}

    proxy_df["venue_norm"] = proxy_df["venue"].map(_normalize_name)
    proxy_df["city_norm"] = proxy_df["city"].map(_normalize_name)
    proxy_df["season"] = proxy_df["season"].astype(int)
    proxy_df["is_four"] = (proxy_df["runs_batter"] == 4).astype(int)
    proxy_df["is_124"] = proxy_df["runs_batter"].isin([1, 2, 4]).astype(int)

    grouped = proxy_df.groupby(["venue_norm", "city_norm", "season"], dropna=False).agg(
        total_balls=("runs_batter", "size"),
        fours=("is_four", "sum"),
        one_two_four=("is_124", "sum"),
    ).reset_index()

    grouped["boundary_to_ball"] = grouped["fours"] / grouped["total_balls"].replace(0, np.nan)
    grouped["four_conversion"] = grouped["fours"] / grouped["one_two_four"].replace(0, np.nan)

    league_boundary = grouped["boundary_to_ball"].mean(skipna=True)
    league_conversion = grouped["four_conversion"].mean(skipna=True)
    if pd.isna(league_boundary) or league_boundary <= 0:
        league_boundary = 1.0
    if pd.isna(league_conversion) or league_conversion <= 0:
        league_conversion = 1.0

    grouped["proxy_index"] = 0.5 * (
        grouped["boundary_to_ball"].fillna(league_boundary) / league_boundary
    ) + 0.5 * (
        grouped["four_conversion"].fillna(league_conversion) / league_conversion
    )

    grouped["outfield_speed"] = grouped["proxy_index"].clip(lower=0.80, upper=1.20).round(3)

    # Avoid very noisy estimates from tiny venue-season samples.
    grouped = grouped[grouped["total_balls"] >= 60]
    inferred_map = {
        (row["venue_norm"], row["city_norm"], int(row["season"])): float(row["outfield_speed"])
        for _, row in grouped.iterrows()
    }

    print(f"Built inferred outfield_speed proxies for {len(inferred_map)} venue-seasons.")
    return inferred_map


def _import_player_styles(cursor, conn, player_map):
    styles_df = _first_existing_csv(PLAYER_STYLE_CANDIDATES)
    if styles_df is None:
        print("No player style source found; leaving batting/bowling style columns null.")
        return

    columns = {str(col).strip().lower(): col for col in styles_df.columns}
    name_cols = [columns.get(key) for key in ["player_name", "full_name", "unique_name", "player", "name"] if key in columns]
    batting_col = next((columns.get(key) for key in ["batting_style", "batting hand", "bat_style", "bat_hand"] if key in columns), None)
    bowling_arm_col = next((columns.get(key) for key in ["bowling_arm", "bowling_style", "arm", "bowl_style"] if key in columns), None)
    bowling_type_col = next((columns.get(key) for key in ["bowling_type", "bowling kind", "type", "pace_spin", "bowl_style"] if key in columns), None)

    if not name_cols:
        print("Player style file found, but no player name columns could be resolved.")
        return

    normalized_players = {}
    for name, pid in player_map.items():
        for alias in _name_aliases(name):
            normalized_players.setdefault(alias, pid)

    alias_map = _build_player_alias_map(player_map)
    updated = 0
    for _, row in styles_df.iterrows():
        player_id = _resolve_player_id(row, name_cols, normalized_players, alias_map)
        if not player_id:
            continue

        batting_style = _normalize_batting_style(row.get(batting_col)) if batting_col else None
        bowling_arm = _normalize_bowling_arm(row.get(bowling_arm_col)) if bowling_arm_col else None
        bowling_type = _normalize_bowling_type(row.get(bowling_type_col)) if bowling_type_col else None

        cursor.execute(
            """
            UPDATE players
            SET batting_style = COALESCE(%s, batting_style),
                bowling_arm = COALESCE(%s, bowling_arm),
                bowling_type = COALESCE(%s, bowling_type)
            WHERE player_id = %s
            """,
            (batting_style, bowling_arm, bowling_type, player_id),
        )
        updated += 1

    conn.commit()
    print(f"Applied player style enrichment for {updated} players.")


def _import_venue_conditions(cursor, conn, venue_map, inferred_outfield_map=None):
    conditions_df = _first_existing_csv(VENUE_CONDITION_CANDIDATES)
    if conditions_df is None:
        print("No venue conditions source found; leaving boundary/outfield columns null.")
        return

    columns = {str(col).strip().lower(): col for col in conditions_df.columns}
    venue_col = next((columns.get(key) for key in ["venue_name", "venue", "ground"] if key in columns), None)
    city_col = next((columns.get(key) for key in ["city"] if key in columns), None)
    season_col = next((columns.get(key) for key in ["season", "year"] if key in columns), None)
    boundary_col = next((columns.get(key) for key in ["boundary_distance_m", "boundary_distance", "boundary"] if key in columns), None)
    outfield_col = next((columns.get(key) for key in ["outfield_speed", "outfield"] if key in columns), None)

    if venue_col is None or season_col is None:
        print("Venue conditions file found, but venue or season columns could not be resolved.")
        return

    normalized_venues = {(_normalize_name(v), _normalize_name(c)): vid for (v, c), vid in venue_map.items()}
    upserted = 0
    csv_outfield_count = 0
    inferred_outfield_count = 0
    missing_outfield_count = 0
    inferred_outfield_map = inferred_outfield_map or {}
    for _, row in conditions_df.iterrows():
        venue_norm = _normalize_name(row.get(venue_col))
        city_norm = _normalize_name(row.get(city_col)) if city_col else ""
        venue_key = (venue_norm, city_norm)
        venue_id = normalized_venues.get(venue_key)
        if not venue_id:
            continue

        try:
            season = int(row.get(season_col))
        except (TypeError, ValueError):
            continue

        boundary_distance = _null_if_blank(row.get(boundary_col)) if boundary_col else None
        outfield_speed = _null_if_blank(row.get(outfield_col)) if outfield_col else None

        if outfield_speed is None:
            inferred_value = inferred_outfield_map.get((venue_norm, city_norm, season))
            if inferred_value is not None:
                outfield_speed = inferred_value
                inferred_outfield_count += 1
            else:
                missing_outfield_count += 1
        else:
            csv_outfield_count += 1

        cursor.execute(
            """
            INSERT INTO venue_conditions (
                venue_id, season, boundary_distance_m, outfield_speed
            ) VALUES (%s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                boundary_distance_m = VALUES(boundary_distance_m),
                outfield_speed = VALUES(outfield_speed)
            """,
            (
                venue_id,
                season,
                boundary_distance,
                outfield_speed,
            ),
        )
        upserted += 1

    conn.commit()
    print(f"Applied venue condition enrichment for {upserted} venue-seasons.")
    print(
        "Outfield speed coverage: "
        f"csv={csv_outfield_count}, inferred={inferred_outfield_count}, missing={missing_outfield_count}."
    )


if __name__ == "__main__":
    main()
